version: '3.8'

services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: australian-payment-api
    ports:
      - "3232:3232"
    environment:
      - NODE_ENV=production
      - PORT=3232
      - HOST=0.0.0.0
      - API_VERSION=v1
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3232/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - payment-network

  # Development service with hot reload
  payment-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: australian-payment-api-dev
    ports:
      - "3232:3232"
    environment:
      - NODE_ENV=development
      - PORT=3232
      - HOST=0.0.0.0
      - API_VERSION=v1
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge